
name: Publish
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Activate melos
        run: dart pub global activate melos 2.9.0
      - name: Login pub
        run: |
          mkdir -p "$XDG_CONFIG_HOME/dart/"
          echo "${{ secrets.PUB_CREDENTIALS}}" | base64 -d > "$XDG_CONFIG_HOME/dart/pub-credentials.json"
      - name: Validate publish
        run: melos publish --dry-run --yes
      - name: Publish
        run: melos publish --no-dry-run --yes
